##DEFINIR REGRAS DE NEGÓCIO PARA O ESTOQUE

#EXEMPLO2 ---> FUNÇÃO QUE VERIFICA E AVISA SE ALGUM PRODUTO ATINGIU A QUANTIDADE MÍNIMA DO ESTOQUE ESTABELECIDO PARA ELE

#EXEMPLO3 ---> FUNÇÃO QUE EMITE NOTIFICAÇÃO SOBRE OS PRODUTOS QUE ESTÃO COM O ESTOQUE BAIXO

